/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.PnlVehicleController;
import controllers.PnlViewVehicleController;
import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.util.Observer;
import panels.PnlVehicle;
import panels.PnlViewVehicles;

/**
 *
 * @author Sistemas-07
 */
public class DlgVehicle extends javax.swing.JDialog {
     
    private PnlVehicle pnlVehicle;
    private PnlVehicleController pnlVehicleController;
    
    PnlViewVehicles pnlViewVehicle = null;
    PnlViewVehicleController pnlViewVehicleController = null;
    
    /**
     * Creates new form DlgVehicle
     */
    public DlgVehicle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void addObserver(Observer ob){
        pnlVehicleController.addObserver(ob);
    }

    public PnlViewVehicles getPnlViewVehicle() {
        return pnlViewVehicle;
    }

    public PnlViewVehicleController getPnlViewVehicleController() {
        return pnlViewVehicleController;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlVehicle = new PnlVehicle();
        try{
            pnlVehicleController = new PnlVehicleController(pnlVehicle);
        }catch(FileNotFoundException ext){

        }

        pnlVehicleController.setIsNew(true);
        pnlContent.add(pnlVehicle, BorderLayout.CENTER);

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(551, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        bindingDataToComponents();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    public void setPnlViewVehicleReference(PnlViewVehicles pnlViewVehicles, PnlViewVehicleController pnlViewVehicleController)
    {
        this.pnlViewVehicle = pnlViewVehicles;
        this.pnlViewVehicleController = pnlViewVehicleController;
        
        if(pnlViewVehicle == null)
            return;
    }
    public void bindingDataToComponents() {
        if(pnlViewVehicle == null)
            return;
        int row = pnlViewVehicle.getTblViewVehicle().getSelectedRow();
        bindingDataToComponents(row);
    }
    
    /*public void setSelectedRow(int row) {
        pnlViewVehicle.getTblViewVehicle().getSelectionModel().setSelectionInterval(row, row);
    }*/
    
    public void bindingDataToComponents(int row) {

        pnlVehicle.getTxtStock().setText(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 0).toString().trim());
        pnlVehicle.getSpnYear().setValue(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 1));
        pnlVehicle.getCmbMake().setSelectedItem(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 2).toString().trim());
        pnlVehicle.getCmbModel().setSelectedItem(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 3).toString().trim());
        pnlVehicle.getTxtStyle().setText(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 4).toString().trim());
        pnlVehicle.getFmtVin().setText(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 5).toString().trim());
        pnlVehicle.getCmbEColor().setSelectedItem(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 6).toString().trim());
        pnlVehicle.getCmbIColor().setSelectedItem(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 7).toString().trim());
        //Integer.parseInt(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 8).toString())
        Integer miles = Integer.parseInt(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 8).toString());
        Double price = Double.parseDouble(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 9).toString());
        pnlVehicle.getSpnMiles().getModel().setValue(miles);
        pnlVehicle.getSpnPrice().getModel().setValue(price);
        
        if(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 10).toString() == "AUTOMATIC")
            pnlVehicle.getBtngTrans().setSelected(pnlVehicle.getRbtnAut().getModel(), true);
        else
            pnlVehicle.getBtngTrans().setSelected(pnlVehicle.getRbtnMan().getModel(), true);
        pnlVehicle.getTxtEngine().setText(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 11).toString().trim());
        pnlVehicle.getTxtImage().setText(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 12).toString().trim());
        pnlVehicle.getCmbStatus().setSelectedItem(pnlViewVehicle.getTblViewVehicle().getValueAt(row, 13).toString().trim());
        
        //int vehicleId = pnlViewVehicleController.getVehicles().get(row).getId();
        int id = (int) pnlViewVehicle.getTblViewVehicle().getValueAt(pnlViewVehicle.getTblViewVehicle().getSelectedRow(), 14);

        pnlVehicleController.setVehicleIdToEdit(id);
        pnlVehicleController.setIsUpdate(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgVehicle dialog = new DlgVehicle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
