/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import backend.dao.implementation.JsonVehicleDaoImpl;
import backend.pojo.Vehicle;
import controllers.PnlVehicleController;
import controllers.PnlViewVehicleController;
import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.VehicleTableModel;
import panels.PnlVehicle;
import panels.PnlViewVehicles;

/**
 *
 * @author Sistemas-07
 */
public class IfmVehicleView extends javax.swing.JInternalFrame {
    private DlgVehicle dlgVehicle;
    
    private PnlViewVehicles pnlViewVehicles;
    private PnlViewVehicleController pnlViewVehicleController;
    /**
     * Creates new form IfmVehicleView
     */
    public IfmVehicleView() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlContent = new javax.swing.JPanel();
        PnlBotones = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vehicles");

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlViewVehicles = new PnlViewVehicles();
        pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicles);

        pnlContent.add(pnlViewVehicles, BorderLayout.CENTER);
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        PnlBotones.setBackground(new java.awt.Color(204, 204, 204));

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });
        PnlBotones.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdateActionPerformed(evt);
            }
        });
        PnlBotones.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });
        PnlBotones.add(btnDelete);

        getContentPane().add(PnlBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(pnlViewVehicles.getTblViewVehicle().getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila si desea eliminarla.",
                    "Delete message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this row?","Delete", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.NO_OPTION)
            return;
        
        int row = pnlViewVehicles.getTblViewVehicle().getSelectedRow();
        int vehicleId = (int) pnlViewVehicles.getTblViewVehicle().getValueAt(pnlViewVehicles.getTblViewVehicle().getSelectedRow(), 14);

        Vehicle vehicle = new Vehicle();
        vehicle.setId(vehicleId);
        JsonVehicleDaoImpl jsonVehicleDaoImpl;
        try
        {
            jsonVehicleDaoImpl = new JsonVehicleDaoImpl();
            jsonVehicleDaoImpl.delete(vehicle);
            
            VehicleTableModel dtm =  (VehicleTableModel) pnlViewVehicles.getTblViewVehicle().getModel(); 
            dtm.removeRow(row);
            
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(IfmVehicleView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(IfmVehicleView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        JOptionPane.showMessageDialog(null, "The row was sucessfully deleted",
                "Delete message",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        dlgVehicle = new DlgVehicle(null,true);
        dlgVehicle.addObserver(pnlViewVehicleController.getTblViewModel());
        dlgVehicle.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdateActionPerformed
    {//GEN-HEADEREND:event_btnUpdateActionPerformed
        if(pnlViewVehicles.getTblViewVehicle().getSelectedRow() == -1)
        { 
            JOptionPane.showMessageDialog(null, "Seleccione una fila si desea editar sus campos.",
                    "Updating message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DlgVehicle dlgVehicle = new DlgVehicle(null, true);
        //dlgVehicle.addObserver(pnlViewVehicleController.getTblViewModel());  //Pendiente 
        dlgVehicle.setPnlViewVehicleReference(pnlViewVehicles, pnlViewVehicleController);
        
        dlgVehicle.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBotones;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
