/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panels;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author UZIEL
 */
public class PnlTemperatura extends javax.swing.JPanel
{

    /**
     * Creates new form PnlTemperatura
     */
    public PnlTemperatura()
    {
        initComponents();
    }

    public JButton getBtnConvertir()
    {
        return btnConvertir;
    }

    public void setBtnConvertir(JButton btnConvertir)
    {
        this.btnConvertir = btnConvertir;
    }

    public JButton getBtnNuevo()
    {
        return btnNuevo;
    }

    public void setBtnNuevo(JButton btnNuevo)
    {
        this.btnNuevo = btnNuevo;
    }

    public JTextField getTxtA()
    {
        return txtA;
    }

    public void setTxtA(JTextField txtA)
    {
        this.txtA = txtA;
    }

    public JTextField getTxtConvertida()
    {
        return txtConvertida;
    }

    public void setTxtConvertida(JTextField txtConvertida)
    {
        this.txtConvertida = txtConvertida;
    }

    public JTextField getTxtTemperatura()
    {
        return txtTemperatura;
    }

    public void setTxtTemperatura(JTextField txtTemperatura)
    {
        this.txtTemperatura = txtTemperatura;
    }

    public JComboBox<String> getjComboBox1()
    {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1)
    {
        this.jComboBox1 = jComboBox1;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnConvertir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtConvertida = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertir);

        btnNuevo.setText("Nuevo");
        jPanel1.add(btnNuevo);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Celsius a", "De Fahrenheit a" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jComboBox1, gridBagConstraints);

        txtA.setEditable(false);
        txtA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(txtA, gridBagConstraints);

        jLabel1.setText("Temperatura: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(txtTemperatura, gridBagConstraints);

        jLabel2.setText("Temperatura convertida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel2, gridBagConstraints);

        txtConvertida.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(txtConvertida, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtAActionPerformed
    {//GEN-HEADEREND:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConvertirActionPerformed
    {//GEN-HEADEREND:event_btnConvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtConvertida;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
