/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import views.panels.PnlTextEditor;

/**
 *
 * @author UZIEL
 */
public class FrmEditor extends javax.swing.JFrame
{
    private int countTab;
    private FileWriter fw;
    /**
     * Creates new form FrmEditor
     */
    public FrmEditor()
    {
        countTab = 1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tbpContent = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnCloseTab = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnNew = new javax.swing.JMenuItem();
        mnOpen = new javax.swing.JMenuItem();
        mnSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(tbpContent, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnCloseTab.setText("X");
        btnCloseTab.setFocusable(false);
        btnCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCloseTab.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseTabActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCloseTab);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        mnFile.setText("File");

        mnNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Add_132335.png"))); // NOI18N
        mnNew.setText("New");
        mnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnNewActionPerformed(evt);
            }
        });
        mnFile.add(mnNew);

        mnOpen.setText("Open");
        mnOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnOpenActionPerformed(evt);
            }
        });
        mnFile.add(mnOpen);

        mnSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnSaveAs.setText("Save as");
        mnSaveAs.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnSaveAsActionPerformed(evt);
            }
        });
        mnFile.add(mnSaveAs);
        mnFile.add(jSeparator1);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnExitActionPerformed(evt);
            }
        });
        mnFile.add(mnExit);

        jMenuBar1.add(mnFile);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(418, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnNewActionPerformed
    {//GEN-HEADEREND:event_mnNewActionPerformed
        // TODO add your handling code here:
        PnlTextEditor pnlTextEditor = new PnlTextEditor();
        tbpContent.add("Editor" + countTab++, pnlTextEditor);
    }//GEN-LAST:event_mnNewActionPerformed

    private void btnCloseTabActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseTabActionPerformed
    {//GEN-HEADEREND:event_btnCloseTabActionPerformed
        // TODO add your handling code here:
        if(tbpContent.getComponentCount() <= 0)
            return;
        int option = JOptionPane.showConfirmDialog(null, "Are u sure you wanna delete this tab",
                "Confirm Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(option == 1)
            return;
        
        int index = tbpContent.getSelectedIndex();
        tbpContent.remove(index);
    }//GEN-LAST:event_btnCloseTabActionPerformed

    private void mnSaveAsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnSaveAsActionPerformed
    {//GEN-HEADEREND:event_mnSaveAsActionPerformed
        // TODO add your handling code here:
        String nombreArchivo = JOptionPane.showInputDialog("Ingrese nombre del archivo: ");
        try
        {
            fw = new FileWriter("\\src\\main\\archivos" + nombreArchivo + ".txt");
            PnlTextEditor pnlTextEditor = (PnlTextEditor) tbpContent.getSelectedComponent();
            
            String texto = pnlTextEditor.getTxtAEditor().getText();
            fw.write(texto);
            
            fw.close();
            
        } catch (IOException ex)
        {
            Logger.getLogger(FrmEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnSaveAsActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnExitActionPerformed
    {//GEN-HEADEREND:event_mnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnOpenActionPerformed
    {//GEN-HEADEREND:event_mnOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnNew;
    private javax.swing.JMenuItem mnOpen;
    private javax.swing.JMenuItem mnSaveAs;
    private javax.swing.JTabbedPane tbpContent;
    // End of variables declaration//GEN-END:variables
}
