/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.PnlCalculadoraControlador;
import controllers.PnlMonedaControlador;
import controllers.PnlTemperaturaControlador;
import controllers.PnlTemperaturaController;
import java.awt.BorderLayout;
import javax.swing.JComponent;
import views.panels.PnlCalculadora;
import views.panels.PnlConversionTemplate;
import views.panels.PnlMoneda;
import views.panels.PnlTemperatura;

/**
 *
 * @author UZIEL
 */
public class StartFrame extends javax.swing.JFrame
{
    private PnlCalculadora pnlCalculadora;
    private PnlCalculadoraControlador pnlCalculadoraControlador;
    private PnlTemperatura pnlTemperatura;
    private PnlTemperaturaControlador pnlTemperaturaControlador;
    private PnlMoneda pnlMoneda;
    private PnlMonedaControlador pnlMonedaControlador;
    
    private PnlConversionTemplate pnlCTTemperatura;
    private PnlTemperaturaController pnlTemperaturaController;

    /**
     * Creates new form StartFrame
     */
    public StartFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOperaciones = new javax.swing.JPanel();
        btnCalculadora = new javax.swing.JButton();
        btnTemperatura = new javax.swing.JButton();
        btnCambioMoneda = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi app");

        pnlOperaciones.setLayout(new java.awt.GridLayout(3, 1, 2, 2));

        btnCalculadora.setText("Calculadora");
        btnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadoraActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnCalculadora);

        btnTemperatura.setText("Conversion Temperatura");
        btnTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturaActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnTemperatura);

        btnCambioMoneda.setText("Cambio Moneda");
        btnCambioMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioMonedaActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnCambioMoneda);

        getContentPane().add(pnlOperaciones, java.awt.BorderLayout.LINE_START);

        pnlContenido.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(418, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculadoraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalculadoraActionPerformed
    {//GEN-HEADEREND:event_btnCalculadoraActionPerformed
        // TODO add your handling code here:
        if(pnlCalculadora == null)
        {
            pnlCalculadora = new PnlCalculadora();
            pnlCalculadoraControlador = new PnlCalculadoraControlador(pnlCalculadora);
        }
        addComponent(pnlCalculadora);
    }//GEN-LAST:event_btnCalculadoraActionPerformed

    private void addComponent(JComponent component) {
        pnlContenido.removeAll();


        pnlContenido.add(component, BorderLayout.CENTER);
        pnlContenido.repaint();
        this.validate();
    }

    private void btnTemperaturaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTemperaturaActionPerformed
    {//GEN-HEADEREND:event_btnTemperaturaActionPerformed
        // TODO add your handling code here:
        if(pnlCTTemperatura == null)
        {
            pnlCTTemperatura = new PnlConversionTemplate();
            pnlTemperaturaController = new PnlTemperaturaController(pnlCTTemperatura);
        }
        addComponent(pnlCTTemperatura);
    }//GEN-LAST:event_btnTemperaturaActionPerformed

    private void btnCambioMonedaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCambioMonedaActionPerformed
    {//GEN-HEADEREND:event_btnCambioMonedaActionPerformed
        // TODO add your handling code here:
        if(pnlMoneda == null)
        {
            pnlMoneda = new PnlMoneda();
            pnlMonedaControlador = new PnlMonedaControlador(pnlMoneda);
        }
        if(pnlContenido.getComponentCount() > 0)
            pnlContenido.remove(0);
        pnlContenido.add(pnlMoneda, BorderLayout.CENTER);
        this.validate();
    }//GEN-LAST:event_btnCambioMonedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculadora;
    private javax.swing.JButton btnCambioMoneda;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlOperaciones;
    // End of variables declaration//GEN-END:variables
}
