/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import controllers.PnlVehicleTreeController;
import javax.swing.JTree;

/**
 *
 * @author UZIEL
 */
public class PnlVehicleTree extends javax.swing.JPanel
{
    PnlVehicleTreeController pnlVehicleTreeController;
    /**
     * Creates new form PnlVehicleTree
     */
    public PnlVehicleTree()
    {
        initComponents();
        pnlVehicleTreeController = new PnlVehicleTreeController(this);
    }

    public JTree getTreeAccount()
    {
        return treeAccount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeAccount = new javax.swing.JTree();

        setLayout(new javax.swing.OverlayLayout(this));

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));
        add(jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeAccount.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treeAccount);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treeAccount;
    // End of variables declaration//GEN-END:variables
}
