/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import controllers.PnlVehicleTreeController;
import javax.swing.JPanel;
import javax.swing.JTree;

/**
 *
 * @author UZIEL
 */
public class PnlVehicleTree extends javax.swing.JPanel
{
    PnlVehicleTreeController pnlVehicleTreeController;
    /**
     * Creates new form PnlVehicleTree
     */
    public PnlVehicleTree()
    {
        initComponents();
        pnlVehicleTreeController = new PnlVehicleTreeController(this);
    }

    public JTree getTreeAccount()
    {
        return treeAccount;
    }

    public JPanel getPnlData()
    {
        return pnlData;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeAccount = new javax.swing.JTree();
        pnlData = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeAccount.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(treeAccount);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.LINE_START);

        pnlData.setBackground(new java.awt.Color(204, 204, 204));
        pnlData.setLayout(new java.awt.BorderLayout());
        add(pnlData, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlData;
    private javax.swing.JTree treeAccount;
    // End of variables declaration//GEN-END:variables
}
